### ISSUE TITLE
Signature validation error on agent node

### ISSUE THREAD

**Issue by kenhuang** [bcgov/greenlight#239]
Any reason we getting the following error from bc-registries pod when try to point to our own INDY_LEDGER_URL, using the default http://dev.dflow.bcovrin.vonx.io is working fine.

Our hosted indy-node version: 1.6.862
dev.dflow.bcovrin.vonx.io  indy-node version: 1.6.636 

I'm using the master branch of von-network to start the network.

```
2019-05-15 22:52:23,215 INFO [von_anchor.anchor.base]: BaseAnchor.get_cred_def: got cred def 7eHEtryQf1pgL5MEiTLZPe:3:CL:10:tag from ledger
2019-05-15 22:52:23,215 INFO [vonx.indy.service]: Indy agent synced: bcreg
2019-05-15 22:52:23,488 ERROR [vonx.common.service]: Error during indy sync: 
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/common/service.py", line 177, in _sync
    synced = await self._service_sync()
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/indy/service.py", line 211, in _service_sync
    if not await self._sync_connection(connection):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/indy/service.py", line 424, in _sync_connection
    connection.connection_id, str(e))) from None
vonx.common.service.ServiceSyncError: Error syncing connection bcreg: Bad response from post_json: (400) Signature validation error
2019-05-15 22:52:23,494 INFO [vonx.common.service]: Starting sync: indy
2019-05-15 22:52:23,557 ERROR [vonx.common.service]: Error during indy sync: 
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/common/service.py", line 177, in _sync
    synced = await self._service_sync()
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/indy/service.py", line 211, in _service_sync
    if not await self._sync_connection(connection):
  File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vonx/indy/service.py", line 424, in _sync_connection
    connection.connection_id, str(e))) from None
vonx.common.service.ServiceSyncError: Error syncing connection bcreg: Bad response from post_json: (400) Signature validation error
```

Webserver log from our hosted von-network:
```
...
INFO:aiohttp.access:52.205.36.114 [15/May/2019:22:50:22 +0000] "GET /genesis HTTP/1.1" 200 3229 "-" "Python/3.6 aiohttp/3.3.2"
INFO:server.anchor:Register agent
INFO:server.anchor:Get nym: 7eHEtryQf1pgL5MEiTLZPe
INFO:server.anchor:Send nym: 7eHEtryQf1pgL5MEiTLZPe/4czTgkgBgwqGaDURfwEm7sEMUYQKWcU1vZYtnyvUz8xG
INFO:aiohttp.access:52.205.36.114 [15/May/2019:22:50:28 +0000] "POST /register HTTP/1.1" 200 303 "-" "Python/3.6 aiohttp/3.3.2"
...
```

**Comment by ianco** [comment]
You need to make sure you reset the whole environment when you switch ledgers.  For example, when you create a credential definition there is crypto that is put in the wallet that has to match what is on the ledger.  So if you initialize everything on one ledger, then switch to another with the same wallet, the crypto info in your wallet associated with your credential definitions won't match, and you can't sign credentials.

If you want to switch ledgers, you need to do a full environment reset ("./manage rm" in all shells), then reset everything to point to the new ledger, then "./manage start" everywhere.

**Comment by kenhuang** [comment]
Thanks for the suggestion, after reset theorgbook deployment with the correct INDY_LEDGER_URL everything work together now.
